### ISSUE TITLE
SIGSEGV when subscribing to laser scans 

### ISSUE THREAD

**Issue by maxlein** [ros2/rviz#485]
I get repeated seg faults when subscribing to laser scans and having a fixed frame other than the laser scans frame.  It doesn't crash immediatelly but after a few seconds.  

I also get a bunch of these messages although all frames exist:  

```
Warning: Invalid frame ID "front_wheel" passed to canTransform argument source_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-eloquent-tf2-0.12.4/src/buffer_core.cpp
[INFO 1575306955.509136181] [rviz]: Message Filter dropping message: frame 'front_scanner_link' at time 2043.850 for reason 'Unknown'
Warning: Invalid frame ID "front_steering" passed to canTransform argument source_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-eloquent-tf2-0.12.4/src/buffer_core.cpp
Warning: Invalid frame ID "front_wheel" passed to canTransform argument source_frame - frame does not exist
```

Frames published by gazebo/static publishers:  

```
Frames:
Frame: /base_link, published by <no authority available>, Average Delay: 0.00129136, Max Delay: 0.0109406
Frame: /fork, published by <no authority available>, Average Delay: 1.5753e+09, Max Delay: 1.5753e+09
Frame: /front_scanner_link, published by <no authority available>, Average Delay: 0.00128887, Max Delay: 0.0109382
Frame: /left_wheel, published by <no authority available>, Average Delay: 1.5753e+09, Max Delay: 1.5753e+09
Frame: /right_wheel, published by <no authority available>, Average Delay: 1.5753e+09, Max Delay: 1.5753e+09
Frame: chassis, published by <no authority available>, Average Delay: 1.5753e+09, Max Delay: 1.5753e+09
Frame: fork, published by <no authority available>, Average Delay: 1.5753e+09, Max Delay: 1.5753e+09
Frame: left_wheel, published by <no authority available>, Average Delay: 1.5753e+09, Max Delay: 1.5753e+09
Frame: odom, published by <no authority available>, Average Delay: -0.299721, Max Delay: 0
Frame: right_wheel, published by <no authority available>, Average Delay: 1.5753e+09, Max Delay: 1.5753e+09
```

```
Core was generated by `rviz2'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0a58436320 in tf2_ros::MessageFilter<sensor_msgs::msg::LaserScan_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>::transformReadyCallback(std::shared_future<geometry_msgs::msg::TransformStamped_<std::allocator<void> > > const&, unsigned long) () from /opt/ros/eloquent/lib/librviz_default_plugins.so
[Current thread is 1 (Thread 0x7f0aaddaff80 (LWP 7237))]
(gdb) backtrace
#0  0x00007f0a58436320 in tf2_ros::MessageFilter<sensor_msgs::msg::LaserScan_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>::transformReadyCallback(std::shared_future<geometry_msgs::msg::TransformStamped_<std::allocator<void> > > const&, unsigned long) () from /opt/ros/eloquent/lib/librviz_default_plugins.so
#1  0x00007f0a571b1ebf in ?? () from /opt/ros/eloquent/lib/libtf2_ros.so
#2  0x00007f0a56b72fd4 in tf2::BufferCore::testTransformableRequests() () from /opt/ros/eloquent/lib/libtf2.so
#3  0x00007f0a56b741a2 in tf2::BufferCore::setTransformImpl(tf2::Transform const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) () from /opt/ros/eloquent/lib/libtf2.so
#4  0x00007f0a56b74597 in tf2::BufferCore::setTransform(geometry_msgs::msg::TransformStamped_<std::allocator<void> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
    () from /opt/ros/eloquent/lib/libtf2.so
#5  0x00007f0a571b841e in tf2_ros::TransformListener::subscription_callback(std::shared_ptr<tf2_msgs::msg::TFMessage_<std::allocator<void> > >, bool) () from /opt/ros/eloquent/lib/libtf2_ros.so
#6  0x00007f0a585dc6a8 in std::_Function_handler<void (std::shared_ptr<tf2_msgs::msg::TFMessage_<std::allocator<void> > >), std::_Bind<void (tf2_ros::TransformListener::*(tf2_ros::TransformListener*, std::_Placeholder<1>, bool))(std::shared_ptr<tf2_msgs::msg::TFMessage_<std::allocator<void> > >, bool)> >::_M_invoke(std::_Any_data const&, std::shared_ptr<tf2_msgs::msg::TFMessage_<std::allocator<void> > >&&) ()
   from /opt/ros/eloquent/lib/librviz_default_plugins.so
#7  0x00007f0a585e1f7d in rclcpp::AnySubscriptionCallback<tf2_msgs::msg::TFMessage_<std::allocator<void> >, std::allocator<void> >::dispatch(std::shared_ptr<tf2_msgs::msg::TFMessage_<std::allocator<void> > >, rmw_message_info_t const&) () from /opt/ros/eloquent/lib/librviz_default_plugins.so
#8  0x00007f0a585e23e0 in rclcpp::Subscription<tf2_msgs::msg::TFMessage_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<tf2_msgs::msg::TFMessage_<std::allocator<void> >, std::allocator<void> > >::handle_message(std::shared_ptr<void>&, rmw_message_info_t const&) () from /opt/ros/eloquent/lib/librviz_default_plugins.so
#9  0x00007f0aac3c7cef in rclcpp::executor::Executor::execute_subscription(std::shared_ptr<rclcpp::SubscriptionBase>) () from /opt/ros/eloquent/lib/librclcpp.so
#10 0x00007f0aac3c9015 in rclcpp::executor::Executor::execute_any_executable(rclcpp::executor::AnyExecutable&) () from /opt/ros/eloquent/lib/librclcpp.so
#11 0x00007f0aac3cbbfe in rclcpp::executor::Executor::spin_some(std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /opt/ros/eloquent/lib/librclcpp.so
#12 0x00007f0aad98b78f in rviz_common::VisualizationManager::onUpdate() () from /opt/ros/eloquent/lib/librviz_common.so
#13 0x00007f0aacb58645 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f0aacb650b7 in QTimer::timeout(QTimer::QPrivateSignal) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f0aacb65418 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f0aacb5916b in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f0aad13e83c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f0aad146104 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f0aacb299c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f0aacb81e1e in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f0aacb825e1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f0aa7b24417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f0aa7b24650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f0aa7b246dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007f0aacb8297f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007f0aacb279fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007f0aacb30aa4 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

```

**Comment by jacobperron** [comment]
@maxlein Correct me if you think I'm mistaken, but I think this is the same issue as https://github.com/ros2/geometry2/issues/213. I'm going to close this, but feel free to still comment if you think otherwise.
